spring:
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securitydemo
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      web-stat-filter:
        enabled: true
mybatis-plus:
  mapper-locations: mapper/*.xml
